### ISSUE TITLE
Question about Verification process

### ISSUE THREAD

**Issue by MORPHtok** [ElrondNetwork/assets#539]
Hello,

What's the standard lead time between PR opening and first feedback from the team ?
Something wrong with PR for MPH branding or have we just to wait a bit more ?

Regards

Sja

**Comment by ElrondBuds** [comment]
I'm in same situation, not sure how things works here.
There is any telegram chat where we talk about it?

**Comment by Monarchus** [comment]
The same situation here! It seems that the process takes much longer than originally anticipated, or Elrond Team has taken a break in this regard.

**Comment by MORPHtok** [comment]
Seems to have some VIP tokens with fast tracked process. If true, this is clearly unfair since it's not shared and knowned by everyone.

**Comment by Monarchus** [comment]
> Seems to have some VIP tokens with fast tracked process. If true, this is clearly unfair since it's not shared and knowned by everyone.

I noticed that to! If so, this is certainly not the line that Elrond Network has shown us over time as a behavior toward the community. I continue to hope that it is just a situation of conjuncture. Anyway, we all noticed that there are certain projects that are preferred over others and all this without having a clear explanation from the team.

**Comment by Monarchus** [comment]
> Seems to have some VIP tokens with fast tracked process. If true, this is clearly unfair since it's not shared and knowned by everyone.

Like #502

**Comment by MORPHtok** [comment]
The problem here is not the fact that we have to wait and some other not...
Main issue is the total lack of feedback...
