### ISSUE TITLE
Pull request with the assets for "BSK-baa025"

### ISSUE THREAD

**Issue by serban-marius** [ElrondNetwork/assets#8]
I want to push the assets of "BSK-baa025" but I don't have push access to the repository.
Is it only for the Elrond team? Or the members of the community can push our assets in here?
Thanks!

**Comment by MWFIAE** [comment]
With github you normally don't push directly to the main repository, but instead fork it and then make a pull request back in the original repository :)

**Comment by serban-marius** [comment]
Yeah! That totally worked. Thanks @MWFIAE
